.fixtures.yml
manifests/apache.pp
manifests/config.pp
manifests/database.pp
manifests/init.pp
manifests/install.pp
metadata.json
templates/pulpcore-api.service.erb
templates/pulpcore-content.service.erb
templates/pulpcore-resource-manager.service.erb
templates/pulpcore-worker@.service.erb
templates/settings.py.erb

In this PR, I have:
1. Changed default user, group, and paths to use 'pulp' instead of 'pulpcore' as required  by the migration tool
2. Shorted parameter names by removing redundant 'pulp_' prefixes
3. Commented parameters in manifests/init.pp
4. Added random generation of DB password

fixed default params

---

manifests/apache.pp
manifests/init.pp

This resolves #11 and is needed for installer support since some scenarios require the apache vhost to be managed by another module

apache vhost can be externally managed

---

manifests/apache.pp

I noticed this while working on the vhost fragment for foreman-proxy-content. Changing the way the api_url and content_url are defined here should ensure they are defined consistently with the api_path and content_path.

improve declaration of api and content urls

---

manifests/install.pp

`centos-release-scl-rh` is already installed on test setups and doesn't need to be enabled in the main module.

don't enable software collections

---

manifests/apache.pp

We have redundantly defined reverse proxy urls which are not necessary for the service to function. This PR removes them.

remove redundant reverse proxy declarations

---

manifests/config.pp

When the settings file changes, the `MEDIA_ROOT` might change which means the files should be collected again. This also ensures the settings file has been generated before collection happens.

Refresh collectstatic on the settings file

---

manifests/admin.pp
manifests/config.pp
manifests/database.pp
spec/defines/admin_spec.rb

This is essentially a wrapper around django-admin with the right settings.

Introduce a pulpcore::admin define

---

manifests/init.pp

This PR keeps `$facts['fqdn']` as the default `$servername` but allows it to be configurable.
I believe this is necessary to pass `servername => $foreman::servername` as a parameter to `pulpcore` as in https://github.com/theforeman/puppet-foreman_proxy_content/pull/222

make servername configurable

---

spec/acceptance/basic_spec.rb
spec/acceptance/plugins_spec.rb
spec/spec_helper_acceptance.rb

This makes sure we can run without EPEL and is closer to our actual deployment.

Run acceptance tests with SCL redis

---

templates/settings.py.erb

Fixes #28654
This patch updates settings.py to include REMOTE_USER_ENVIRONMENT_NAME = 'HTTP_REMOTE_USER'. This, along with a change to the vhost in puppet-foreman_proxy_content, will be necessary to support client cert auth with pulp3.

Fixes #28654 - support client cert auth with pulp3

---

manifests/init.pp
spec/classes/pulpcore_spec.rb
templates/settings.py.erb

Fixes #28904 - make REMOTE_USER_ENVIRON_NAME configurable

---

manifests/database.pp
manifests/init.pp
spec/classes/pulpcore_spec.rb
templates/settings.py.erb

Fixes #28901 - support external postgresql

---

Rakefile

Modulesync will overwrite this, but I'll write a patch for that when we do another round.

Verify everything to have documented parameters

---

spec/acceptance/basic_spec.rb
spec/acceptance/plugins_spec.rb
spec/spec_helper_acceptance.rb

Also updates the SCL from pg 10 to 12.

Prepare acceptance tests for EL8

---

Gemfile

The selinux_python_command fact in puppet-selinux is incompatible with Facter 4 when testing on non-Red Hat distributions.

Pin Facter to < 4

---

spec/spec_helper_acceptance.rb

This should resolve (rather, hide) the other idempotence issue in the el7 acceptance tests, by ensuring the redis packages are installed already at the time our catalogue is compiled.

install rh-redis5-redis in el7 acceptance spec

---

README.md
manifests/init.pp
spec/classes/pulpcore_spec.rb
templates/settings.py.erb

We are working on getting pulpcore3.2 built and released. This is required to support the changes required to pulp/settings 
@wbclark : This is the the only place I identified a need for changes to support pulpcore 3.2 with this module. Is there anything else that you can think of that needs to be done?

Fixes #29371 - Update settings.py for pulpcore3.2

---

Gemfile

This reverts commit 011f84bcaab7b07440a763f39ecdf643f70cda76.
Replaces https://github.com/theforeman/puppet-pulpcore/pull/83 since Travis reporting is broken there.

Revert "Pin Facter to < 4"

---

manifests/database.pp
spec/acceptance/basic_spec.rb
spec/classes/pulpcore_spec.rb

We need to create the default admin user since pulpcore.app.authentication.PulpNoCreateRemoteUserBackend authentication backend does not create it automatically for us.

Create admin user

---

manifests/admin.pp
spec/defines/admin_spec.rb

In pulpcore::admin, there is a `$command` parameter that defaults to `$title`.  However, `$command` is never used, and `${title}` is used inside an exec where the $command ought to be.

Update pulpcore::admin to use the command parameter if it is passed

---

.sync.yml
.travis.yml
metadata.json
spec/setup_acceptance_node.pp

After marking el8 as a supported OS in metadata.json, I can run spec tests using el8 facts:
```
[wclark@perseids puppet-pulpcore]$ SPEC_FACTS_OS=centos-8-x86_64 bundle exec rspec spec/classes/plugin_migration_spec.rb 
...
Finished in 4.83 seconds (files took 5.29 seconds to load)
3 examples, 0 failures
[wclark@perseids puppet-pulpcore]$ SPEC_FACTS_OS=centos-8-x86_64 bundle exec rspec spec/classes/plugin_file_spec.rb 
...
Finished in 4.03 seconds (files took 5.54 seconds to load)
3 examples, 0 failures
[wclark@perseids puppet-pulpcore]$ SPEC_FACTS_OS=centos-8-x86_64 bundle exec rspec spec/classes/plugin_container_spec.rb 
...
Finished in 3.8 seconds (files took 5.1 seconds to load)
3 examples, 0 failures
[wclark@perseids puppet-pulpcore]$ SPEC_FACTS_OS=centos-8-x86_64 bundle exec rspec …
```

Fixes #29190 - Support EL8

---

metadata.json

6.x was breaking since it made repository management modules soft dependencies. Since we don't use these, it's not breaking here.

Allow puppet/redis 6.x

---

manifests/plugin/certguard.pp
spec/classes/plugin_certguard_spec.rb

Install rhsm package for el7. Dependent on https://github.com/theforeman/foreman-packaging/pull/5363

Fixes #30133 - Install python3-subscription-manager-rhsm

---

manifests/plugin/certguard.pp
spec/classes/plugin_certguard_spec.rb

python3-subscription-manager-rhsm is needed on both EL7 and EL8. On EL7 it's not part of the base OS since rhsm is using Python 2. On EL8 it's installed when subscription-manager is. However, it's good to be explicit about what you need to function. Likely to be present is not good enough.

Refs #30133 - Unconditionally install RHSM

---

manifests/admin.pp
manifests/database.pp
spec/acceptance/basic_spec.rb
spec/classes/pulpcore_spec.rb
spec/defines/admin_spec.rb

This requires at least Pulp 3.2.0, but since f59265ebb9fbe9cceddad37400849f8935538d1e that's been the required minimum version.

Use pulpcore-manager

---

spec/acceptance/basic_spec.rb
spec/acceptance/plugins_spec.rb
spec/support/acceptance/curl_command.rb

This aims to reduce the duplication in curl verifications and also allows checking both the body and the response code.
Since this is also usable outside of puppet-pulpcore, I aim to add this in a reusable place. This PR is here to verify it works in CI and share.

Introduce a curl_command helper

---

templates/settings.py.erb

CONTENT_ORIGIN needs to be poitned at https:// for the
/pulp/container/ redirect to work properly

Refs #30780 - set proper content origin setting

---

manifests/config.pp
manifests/init.pp
manifests/static.pp
spec/classes/pulpcore_spec.rb
templates/pulpcore-api.service.erb
templates/settings.py.erb

Since 8c66bff5f2146139d2882ef75ac742235fe253b1 the pulpcore-manager command runs as root. On a fresh installation this is fine, but on upgrades the user doesn't own /var/lib/pulp/assets. This explicitly manages the static root.
It is split off to a separate class to better capture the dependencies.  The database doesn't need to refresh due to static files, nor any services.

Manage the static assets via a class

---

templates/settings.py.erb

In a reverse proxy setup, the process is running on HTTP only, but Apache is running on both HTTP and HTTPS. To let Django know, Apache sends the X-Forwarded-Proto header[1]. The Django settings documentation suggests this solution[2].
Apache sets these headers by default[3], but I don't know what happens if a clients sets them as well. Does Apache use those or explicitly sets its own?
[1]: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Forwarded-Proto
[2]: https://docs.djangoproject.com/en/2.2/ref/settings/#secure-proxy-ssl-header
[3]: https://httpd.apache.org/docs/current/mod/mod_proxy.html#proxyaddheaders

Handle X-Forwarded-Proto headers

---

manifests/service.pp
templates/pulpcore-api.service.erb
templates/pulpcore-content.service.erb
templates/pulpcore-resource-manager.service.erb
templates/pulpcore-worker@.service.erb

When using systemd, the pid files are actually not important so they can be dropped.
The the WorkingDirectory is set to ~ which will resolve to the user's home directory. That means systemd will ensure it is mounted before starting services. Pulp itself doesn't use it so it's a cheap way for a more reliable service start.
Subscribing to pulpcore-worker@.service is another bugfix to ensure all workers use the correct service definition.
Explicitly setting the type and group is more for consistency and doesn't actually change anything.

Drop pid files and fix working dirs

---

manifests/init.pp
manifests/repo.pp
spec/classes/pulpcore_spec.rb
spec/classes/repo_spec.rb
spec/setup_acceptance_node.pp
templates/repo.epp

This class uses the new yum.theforeman.org repos that are versions per Pulpcore release. This allows easy switching between versions. It also properly sets the GPG key validation.
It does switch acceptance testing from staging repositories to stable repositories. Another implication is that it switches to Pulpcore 3.6 by default. This was chosen since 3.7 is not complete yet.

Add Pulpcore repository class

---

manifests/database.pp

If this is not set, the environment is used. Often this causes the database to be initialized as ASCII which breaks Pulpcore.

Fixes #31018 - Force UTF-8 database encoding

---

README.md
templates/pulpcore-api.service.erb
templates/pulpcore-content.service.erb
templates/pulpcore-resource-manager.service.erb
templates/pulpcore-worker@.service.erb

In python3-pulpcore 3.7.1-2 the `/usr/libexec/pulpcore` wrappers have been introduced to enter the proper SELinux domain.
It has also been cherry picked to 3.6.3-2 but in the SELinux policy is incomplete so it has no effect. The main benefit of that cherry pick is to keep the module compatible with both 3.6 and 3.7.
The README is updated with a support policy. Since 3.7 is not being tested in CI yet, I have not yet added it to the supported versions.

Fixes #30465 - Use libexec wrappers for SELinux

---

templates/pulpcore-api.service.erb
templates/pulpcore-content.service.erb
templates/pulpcore-resource-manager.service.erb
templates/pulpcore-worker@.service.erb

To prevent:
`Oct 09 15:31:27 centos7-64-1 systemd[1]: [/etc/systemd/system/pulpcore-api.service:11] Not an absolute path, ignoring: ~`

use absolute paths in unit files

---

README.md
manifests/apache.pp
manifests/config.pp
manifests/init.pp
manifests/static.pp
spec/classes/pulpcore_spec.rb
templates/settings.py.erb

This explicitly sets the all directories and documents the layout. It diverges from the upstream defaults in that MEDIA_ROOT is set to a subdirectory and the directory permissions are stricter than upstream.  The assets are served in static since this works around some SELinux issue.
Upstream this layout is proposed as the default. https://pulp.plan.io/issues/7178 has been opened for that.
It's an alternative to https://github.com/theforeman/puppet-pulpcore/pull/113. It will need a migration in the installer to move any generated content.

Fixes #30423 - Change the application layout

---

manifests/apache.pp
manifests/config.pp
manifests/init.pp
manifests/service.pp
spec/classes/pulpcore_spec.rb
templates/pulpcore-api.service.erb
templates/pulpcore-api.socket.erb
templates/pulpcore-content.service.erb
templates/pulpcore-content.socket.erb

The use of a Unix socket between the deployed service and the reverse
proxy provides tighter security as the only users who can access the
socket are root and the configured SocketUser. The introduction of
a systemd socket with a ListenStream also provides automatic activation
of the underlying service and safer restarts.
This change is backwards incompatible as it removes the host and port parameters
for the API and Content services in favor of a single bind parameter for each.

Switch to using a Unix socket bind for API and Content services

---

.github/workflows/acceptance.yml
.github/workflows/cron.yml
Gemfile
README.md
manifests/repo.pp

This includes the switch to Github actions, but that needs some work. For example, currently in Travis we have a weekly cronjob to notify us of regressions, but it's still missing in the Github actions part.

Support Pulpcore 3.7

---

manifests/admin.pp

We've seen some reports about pulpcore-manager failures but on the next run it passes. Since there is no log output, this is hard to debug. With this change it will log the failures.

Set logoutput to on_failure for pulpcore::admin

---

manifests/init.pp
spec/classes/pulpcore_spec.rb
templates/settings.py.erb

As part of the new content view import/export API work, we need to be able to add import & export paths to `settings.py`:
```python
ALLOWED_IMPORT_PATHS = ['/var/lib/pulp/sync_imports', '/var/lib/pulp/imports'] # already exists
ALLOWED_EXPORT_PATHS = ['/var/lib/pulp/exports'] # new
```
This PR will be modeled on #79 and adds `ALLOWED_EXPORT_PATHS`.

Fixes #30436 - add allowed_export_paths to settings.py

---

spec/classes/pulpcore_spec.rb

26ea9a0456bf7175b2c9f3228a76d78a68de60e7 moved the tests to a very illogical place. This brings back the correct hierachy for testing.

Correct allowed_{export,import}_paths tests

---

.fixtures.yml
metadata.json
spec/classes/pulpcore_spec.rb

04b9f5f4fbcaafd87c6ea056b9b499197739c7c4 stopped using selinux::port which means the module is no longer used.
Also corrects an assertion around selboolean. a60df532a95dbb3bf951aaf10b85f9b31ba3e635 changed from selinux::boolean to the raw selboolean. While it was true that the resource was never contained, it was no longer correctly testing the logic.

Drop selinux module dependency

---

manifests/config.pp
spec/classes/pulpcore_spec.rb

Ensure that import and export directories are created by the installer.
~~(draft until I finish testing the change)~~

Fixes #31468 - create import/export directories

---

manifests/init.pp

This is recommended by Django and generates a warning about this when doing production checks. Since it's using cached data, this doesn't affect upgrading users.

Increase the secret key size to 50 chars

---

README.md

23bff59eafb60c17ff04561ce55ca8faeb71ebd9 changed the docroot default, but I forgot this entry.

Correct directory tree in README

---

manifests/apache.pp
spec/classes/pulpcore_spec.rb
templates/apache-fragment.epp

Adds a default timeout of 5 minutes to the parameters to address
issues seen when syncing from a Pulp 3 to a Pulp 3 mirror.
The default proxy timeout is 60 seconds, and we have seen in nightly, proxy syncing fail right at the one minute mark. This is a bit of tuning problem so I figured let's start with a higher default of 5 minutes and monitor.

Allow setting parameters on the API and Content Apache proxy

---

manifests/plugin/deb.pp
manifests/plugin/file.pp
manifests/plugin/rpm.pp
spec/classes/plugin_deb_spec.rb
spec/classes/plugin_file_spec.rb
spec/classes/plugin_rpm_spec.rb

For legacy content access, the old Pulp 2 routes are used and proxy directly to the content app rather than redirecting. Thus, they also need to have the proxy parameters such as timeout specified on them.

Add proxy params to plugin Pulp 2 content routes

---

.github/workflows/acceptance.yml
README.md
manifests/config.pp
manifests/init.pp
manifests/repo.pp
spec/classes/pulpcore_spec.rb
templates/settings.py.erb

Pulp 3.9 changes CHUNKED_UPLOAD_DIR from an absolute path to a relative path. It must be within MEDIA_ROOT and there's no need to manage it.  Pulp defaults are correct and overriding it is not recommended upstream.
This does rely on a fix in Pulpcore 3.9.1 which is currently [being worked on](https://github.com/pulp/pulpcore/pull/1078). Hence why this is a draft.
Technically older versions will continue to work but the upload directory may not exist and the pulp user may not have permission to create it. Rather than documenting these, it's chosen to only support the latest version. This also saves CI resources.

Support Pulp 3.9, drop earlier versions

---

manifests/apache.pp

The pulpcore::apache::fragment defines includes pulpcore::apache,
so if used stand-alone will fail since pulpcore::apache relies
upon variables from the main pulpcore class.

Include pulpcore in pulpcore::apache

---

.fixtures.yml

Git master has dropped daemon reloading code which we currently depend on. This pins to the latest released version. I tried to support both, but currently there's no way to distinguish 2.x and 3.x.
https://github.com/theforeman/puppet-pulpcore/pull/176 contains those efforts. https://github.com/camptocamp/puppet-systemd/pull/186 would allow that to work (though there are some other issues).

Pin camptocamp/systemd to 2.12.0 in testing

---

manifests/init.pp
templates/pulpcore-content.service.erb

Upstream pulp_installer uses a default gunicorn worker timeout of 90 seconds[1] for both the content service (which we previously did not configure) and the api service (which we configured to 60 seconds)
[1] https://github.com/pulp/pulp_installer/blob/645887df342f3d06a2aa8ec90740bd41179331c7/roles/pulp_content/templates/pulpcore-content.service.j2#L24

Refs #32112 - Match upstream pulp default api service worker timeout

---

CHANGELOG.md
HISTORY.md
metadata.json

Updating `HISTORY.md` was necessary in this case as changelog generator wanted to make retroactive edits otherwise

Release 3.2.0

---

manifests/admin.pp
spec/defines/admin_spec.rb

Sets a specific directory for pulpcore-manager to be called from.

Fixes #32309 - pulpcore-manager fails from certain directories

---

manifests/apache.pp
manifests/init.pp
spec/classes/pulpcore_spec.rb

…o Pulp as admin
Require a client certificate to be presented with a CN that matches
the supplied auth CN. If this is present, set the REMOTE_USER to
admin to pass along to Pulp. This changes from having to generate
aclient certificate with a valid user (e.g. admin) as the CN
to allowing to use a client certificate generated with a more standard
CN (e.g. FQDN) and act as the admin user.
Example usage:
```
class { 'pulpcore':
api_client_auth_cn => $foreman_host
}
```
Questions:
* This would allow us to drop the special purpose pulp_client certificates we generate today. Do we want to go this route?
* Is this the best way implement how we enable this and configure it?
* This forces all API paths to be behind authentication now. The `/pulp/api/v3/status/` does not require authentication by …

Refs #32383: Configurable client certificate authentication to Pulp

---

manifests/apache.pp

When deploying a stand-alone vhost, Pulp needs these SSL options
set in order for X-CLIENT-CERT to be set.
This fixes an issue for content proxies with Red Hat based content that receive a 403 currently. This should be backported to at least Foreman 2.3.

Fixes #32622: Include StdEnvVars, ExportCertData SSL options in Apache

---

.github/workflows/unit.yml
manifests/admin.pp
manifests/apache.pp
spec/defines/admin_spec.rb

* Dynaconf seems to always be using the current directory. As such, the
cwd could be a directory that is unreadable by the pulp user.  Pulp's
user home must always be readable by the pulp user.
(cherry picked from commit 951a2f823cf57986623329af54f7d060d256e757)

Fixes #32309 - Run admin commands from Pulp's home

---

.fixtures.yml
manifests/service.pp
manifests/socket_service.pp
metadata.json
spec/classes/pulpcore_spec.rb

After [Puppet 5 is dropped](https://github.com/theforeman/puppet-pulpcore/pull/197) camptocamp/systemd 2.x support can be dropped. However, for now I've chosen to support both since I'm not entirely sure if all dependencies in the installer allow 3.x just yet.

Support camptocamp/systemd 3.x

---

manifests/service.pp
manifests/socket_service.pp
spec/classes/pulpcore_spec.rb

This ensures the correct dependency ordering. This is submitted to camptocamp/systemd but we're currently still on 2.x so no update will be available. This also helps with the move to 3.x.
Submitting this now to see if it works in CI, then I can polish it up.

Introduce a private socket_service helper

---

manifests/apache.pp
manifests/plugin/ansible.pp
spec/classes/plugin_ansible_spec.rb

The current value omits the scheme and pulp content path, which causes issues when syncing content across capsules (and probably will cause other failures too).

Fixes #32766 - adds scheme and pulp content path to setting value

---

.github/workflows/ci.yml
README.md
manifests/repo.pp
templates/pulpcore-resource-manager.service.erb
templates/pulpcore-worker@.service.erb

Pulp 3.13 moves to a new wrapper for the worker. This isn't present in older releases so support for them is dropped.

Support Pulp 3.13, drop earlier versions

---

.github/workflows/ci.yml
README.md
manifests/repo.pp

Since nothing in our ecosystem shipped support for 3.13, I chose to drop it for the 3.14 target.

Support 3.14, drop 3.13

---

manifests/init.pp
spec/acceptance/basic_spec.rb
spec/classes/pulpcore_spec.rb
templates/settings.py.erb

Adds a flag to enable content caching via Redis. This is disabled
by default as its a new optional feature in Pulp 3.14.
Requires https://github.com/pulp/pulpcore/pull/1356 being present which is targeted for Pulpcore 3.14. This also updates the README to reflect that minimum version.

Refs #32910: Add ability to enable content caching

---

manifests/init.pp
manifests/service.pp
spec/acceptance/basic_spec.rb
spec/acceptance/disable_new_tasking_system_spec.rb
spec/acceptance/enable_new_tasking_system_spec.rb
spec/acceptance/plugins_spec.rb
spec/acceptance/use_pulp2_content_route_spec.rb
spec/classes/pulpcore_spec.rb
templates/settings.py.erb

This introduces a new parameter `use_legacy_tasking_system` which
defaults to true and configures the application the same as before.
When set to false, pulpcore is configured with the new tasking system
instead. Acceptance tests are included to ensure that users can switch
between the two tasking systems. This is backwards compatible with
Pulpcore versions older than 3.13 ONLY when configured to use the
legacy tasking system. The newer tasking system requires Pulpcore
version >= 3.13.

Fixes #32891 - Add feature to enable new tasking system and enable it by default

---

manifests/database.pp
manifests/init.pp
spec/acceptance/basic_spec.rb
spec/classes/pulpcore_spec.rb
templates/settings.py.erb

This is a more gradual alternative to https://github.com/theforeman/puppet-pulpcore/pull/206
In particular, it doesn't include the ability to enable or disable management of Redis, nor does it consider the content caching feature.
it simply includes the redis class and configures Pulpcore for Redis, based on the value of `use_rq_tasking_system`

Refs #32917 - Don't deploy or configure Redis with new tasking system

---

manifests/database.pp
spec/classes/pulpcore_spec.rb

Without this, the Redis class may not be complete. That means Redis doesn't have to be running by the time the services are started.

Contain Redis within database

---

spec/classes/pulpcore_spec.rb
templates/settings.py.erb

This is shorter in the config, but it also prepares for a connection using a different mechanism. For example, a remote Redis or using a unix socket.

Use REDIS_URL as a configuration option

---

manifests/init.pp
spec/classes/pulpcore_spec.rb

This increases the default API gunicorn worker count to be similar
to that of content worker count but with a smaller minimum. There
are different workloads that can require higher throughput through
the API and the current default of 1 is too low of a starting point.

Fixes #33445: Increase default API gunicorn worker count

---

spec/acceptance/basic_spec.rb
spec/acceptance/worker_count_spec.rb
spec/classes/pulpcore_spec.rb

This commit splits the acceptance tests for worker count changes out
into a separate file, spec/acceptance/worker_count.rb. It also adds
new cases to spec tests to ensure proper interaction of configured
worker_count, previously configured worker_count, and cpu count.

Refactor pulpcore worker_count tests and add additional tests

---

manifests/plugin/rpm.pp
spec/classes/plugin_rpm_spec.rb

This was added to Pulpcore with https://github.com/pulp/pulp_rpm/pull/2333
Backport to 3.14 is underway

Fixes #34298 - support KEEP_CHANGELOG_LIMIT option

---

manifests/install.pp
spec/acceptance/basic_spec.rb

Similar to 5a7991ab90a25aa3add176c1714fc416053a007a but for the group instead of the user.

Fixes #34379 - Create the Pulp group as a system group

---

.github/workflows/ci.yml
.sync.yml
Gemfile

In this repository multiple test suites run. That is currently not supported by gha-puppet so the file becomes unmanaged. It does take the improvement of a test at the end, which allows automerge to be enabled.  It also keeps the Gemfile in sync and aligns on PUPPET_GEM_VERSION.
At the same time it increases the cache version to work around the broken Ruby 2.5 cache which includes Psych 4.

Make it mostly compatible with gha-puppet

---

spec/setup_acceptance_node.pp

Modern tooling prefers the subjectAltName extension and the CN on a certificate is considered deprecated. Some tools even complain about this. However, the -addext command is unavailable on EL7 because openssl is too old.

Generate the acceptance test CA with SAN

---

.github/workflows/ci.yml
README.md
manifests/repo.pp

Looking at the last [Pulpcore version bump](https://github.com/theforeman/puppet-pulpcore/commit/6f09c2ff328fac9fcaf1388d9112a5130db3e2d7), it seems this is all we need to support Pulpcore 3.18.
3.18 is still built for EL7 so we shouldn't have to drop any of the EL7 related bits.

Add Pulpcore 3.18 support

---

manifests/config.pp
manifests/init.pp
spec/classes/pulpcore_spec.rb
spec/type_aliases/logger.rb
spec/type_aliases/loglevel.rb
templates/settings-logging.py.epp
templates/settings.py.erb
types/logger.pp
types/loglevel.pp

This introduces the ability to specify arbitrary loggers with their own log level. While there is currently only a single option, this prepares for future extension.
Additionally, there are default loggers added for pulpcore.deprecation and django_guid. Their levels can still be overridden using the loggers parameter.

Add a loggers parameter and set default loggers

---

.github/workflows/ci.yml
README.md
manifests/repo.pp
spec/support/acceptance/examples.rb

Adding pulpcore 3.21 since we have that packaged. Working on other bits to enable this in katello and gems packaging.

Add pulpcore 3.21 support

---

manifests/init.pp
templates/settings.py.erb

See https://github.com/pulp/pulpcore/issues/3115 for a description of what the telemetry reporting does and how it is configured.
This requires https://github.com/theforeman/puppet-pulpcore/pull/266 and I haven't added any tests yet so I'm marking it as a draft for now.

Fixes #35607 - Configure Pulpcore's TELEMETRY setting

---

templates/settings.py.erb

Since Pulpcore 3.0.0 this setting has been [replaced by CONTENT_ORIGIN](https://pulp.plan.io/issues/5649).

Remove unused CONTENT_HOST setting

---

manifests/apache.pp
manifests/init.pp
spec/classes/pulpcore_spec.rb

This allows setting a CNAME.
Passing the aliases to Apache is especially important when there are multiple vhosts or when using mod_md. While today we don't do either, having the option is good. It can also help with debugging since sosreport does collect the vhosts, but not the certificates. If ServerAliases matches what's on the certificate, that can give a hint.
Currently still working on tests.

Expose Apache server aliases as a parameter

---

manifests/plugin/rpm.pp
spec/classes/plugin_rpm_spec.rb
templates/settings-rpm.py.epp

https://community.theforeman.org/t/katello-incoming-and-existing-advisories-have-the-same-id-but-different-timestamps/23954/8

Add param for unsafe advisory conflict resolution

---

.github/workflows/ci.yml
README.md
manifests/database.pp
manifests/repo.pp

Pulpcore 3.22 will [start using HStore](https://github.com/pulp/pulpcore/pull/3427), which is in postgresql-contrib. This ensures it's installed.
This is all theoretical and I haven't tested this out yet. Just making sure this is tracked somehow.

Fixes #36030 - Ensure HStore is enabled for Pulp 3.22 support

---

.github/workflows/ci.yml

Puppet 8.0.0 was released with incorrect Ruby compatibility metadata, which confuses bundler. This pins to more specific versions.
In gha-puppet this was already done, but this module has a modified beaker pipeline (to run multiple Pulpcore versions) so doesn't benefit from it.

Pin Puppet in CI

---

.github/workflows/ci.yml
README.md
manifests/repo.pp
metadata.json
spec/classes/repo_spec.rb

While it doesn't modify any code, does reduce the testing matrix. It's also chosen because 3.21 and 3.22 have EL9 and that keeps the tesing matrix easier.
Currently untested, going to rely on CI.

Drop Pulpcore 3.16 - 3.18, add EL 9 support

---

spec/classes/pulpcore_spec.rb
templates/pulpcore-api.service.erb
templates/pulpcore-content.service.erb

long options are easier to read and understand

use `--workers` instead of `-w` when configuring gunicorn workers

---

templates/pulpcore-api.service.erb
templates/pulpcore-content.service.erb

this reduces the overall memory usage by keeping only one copy of the code, instead of N (= number of workers).
unscientific benchmark says that with 5 API and 17 content workers, this reduces the memory footprint from 500MiB to 125MiB and from 1.5GiB to 500MiB respectively.
those numbers are obviously before any actual work is executed and memory consumed by the app itself.

Fixes #36437 - preload pulpcore API and content code

---

metadata.json

the breaking changes are dropping Debian 9 and Puppet 6, which is fine for us

allow puppet/redis 9.x

---

spec/setup_acceptance_node.pp

it's outdated and should not be needed anymore in our tests

don't setup ansible-29 repo

---

spec/support/acceptance/examples.rb

Fixes: e93f305df5ae ("Drop testing for Pulpcore 3.16 - 3.18")

Remove leftover from testing Pulpcore < 3.20

---

.github/workflows/ci.yml
.sync.yml
README.md
manifests/repo.pp
spec/classes/repo_spec.rb
templates/pulpcore-api.service.erb
templates/pulpcore-content.service.erb

Assumes that https://github.com/pulp/pulpcore/issues/4679 is in Pulpcore 3.39.
Also assumes that https://github.com/pulp/pulpcore/issues/4681 is going to be fixed for Pulpcore 3.39 in time. This doesn't affect the installer but we shouldn't release Katello with that Pulpcore bug.
I had to assume that the entry point will live in `/usr/bin` since, when installed via `pip`, it is installed to `/usr/local/bin`.
I verified these work (minus the jitter for now):
```
ExecStart=/usr/local/bin/pulpcore-api --preload --timeout 90 --workers 5 --max-requests 800 --access-logfile - --access-logformat 'pulp [%({correlation-id}o)s]: %(h)s %(l)s %(u)s %(t)s "%(r)s" %(s)s %(b)s "%(f)s" "%(a)s"'
```
and
```
ExecStart=/usr/local/bin/pulpcore-content  --preload --timeout 90  --workers 5 --access-logfile - …
```

Fixes #36902 - Support Pulpcore 3.39, drop older versions

---

manifests/init.pp
spec/acceptance/settings_spec.rb
spec/classes/pulpcore_spec.rb
templates/settings.py.erb

Pulp changed the setting name to ANALYTICS. The original name TELEMETRY is deprecated and could be removed in the future. Using pulp's preferred name will also remove the deprecation warning that appears in logs.

Fixes #37062 - Rename pulpcore::telemetry to pulpcore::analytics

---

manifests/database.pp
spec/setup_acceptance_node.pp

Not all systems have this package pre-installed and without it creation of the database will fail.

Ensure glibc-langpack-en is always installed

---

metadata.json

The breaking change was the removal of Debian 10 support, which doesn't affect this module.

Mark compatible with puppet/redis 10.x

---

manifests/plugin/container.pp

Changes the `/pulpcore_registry/v2/`  reverse proxy's `REMOTE_USER` designation so that it always matches the Pulp admin user. Since we use Pulp's remote authentication, the `REMOTE_USER` must always return 'admin' since that is the only user Katello ever interacts with in Pulp.
The goal is to have the location definition look like:
```
<Location "/pulpcore_registry/v2/">
RequestHeader unset REMOTE_USER
RequestHeader set REMOTE_USER "admin" "expr=%{SSL_CLIENT_S_DN_CN} == 'centos8-katello-devel.example.com'"
ProxyPass unix:///run/pulpcore-api.sock|http://pulpcore-api/v2/
ProxyPassReverse unix:///run/pulpcore-api.sock|http://pulpcore-api/v2/
</Location>
```
As currently defined, the REMOTE_USER does not get set and Pulp cannot authenticate requests to push container content to the registry. …

Fixes #37308 - set REMOTE_USER properly for pulpcore registry

---

manifests/database.pp

`--check` is available since Django 3.1 and is nicer than having to grep
for a message that can be different in another language.

use `migrate --check` not `migrate --plan |grep` check for migrations

---

spec/acceptance/cli_spec.rb

new cli is more strict and doesn't accept this

don't add a trailing slash to pulpcore_url in cli tests

---

spec/acceptance/settings_spec.rb

Fixes: ea88d5efe987d0356e0901f10b2b470ab7432b61

fix spec syntax of settings_spec.rb

---

manifests/database.pp
spec/acceptance/hieradata/common.yaml

Pulpcore uses post migration hooks to create data in the database, which
sometimes changes even if there are no real migrations to be run.
This is fine from a Django PoV -- post migration hooks run after every
`migrate` call, even if there have been no changes.
However, this means that we need to run `migrate` unconditionally as
otherwise we might miss changes to the hooks (or their data) when there
is no migration attached.
An example of such a change is
https://github.com/pulp/pulpcore/commit/20cffca49de5f3bfac44e0160c1f0fb262141ea5
where a new role was introduced and our setup started failing as it was
expecting the role to exist after the upgrade, but it did not as we did
not call `migrate`.

Always run pulpcore-manager migrate

---

manifests/plugin/container.pp

We have the exact same code in both pulpcore::plugin::container as in pulpcore::apache. This reuses the variables rather than duplicating the logic.
Fixes: 21aa39e28f19 ("Fixes #37308 - set REMOTE_USER properly for pulpcore registry")

Reuse headers from pulpcore::apache class

---

manifests/apache.pp
manifests/plugin/container.pp
spec/classes/plugin_container_spec.rb
spec/classes/pulpcore_spec.rb
spec/support/acceptance/examples.rb

Those are rejected by Gunicorn 22+, see [1] for details. For older releases of Gunicorn we still unset the underscore notation.
[1] https://github.com/benoitc/gunicorn/issues/2799

Don't use underscores in HTTP headers

---

templates/pulpcore-api.service.erb
templates/pulpcore-content.service.erb
templates/pulpcore-worker@.service.erb

Wants is a weak requirement, so the service won't fail it can't be started but systemd will at least try it. That should work with help when postgresql is local.
This was reported in https://github.com/theforeman/foreman_maintain/issues/824. I don't know if this is sufficient or if foreman_maintain also needs to be smarter.
An open question: if we know PostgreSQL is managed, should we make it a hard `Requires=` instead?

Add Wants=postgresql.service to Pulpcore service files

---

templates/settings.py.erb

database passwords can contain special characters, especially " and '
so we can't just print the value of the field enclosed by single quotes
as that would break whenever the user uses a literal ' in their password

properly escape quotes in passwords by calling to_python

---

manifests/plugin/container.pp
spec/classes/plugin_container_spec.rb

Add `FLATPAK_INDEX=True` to settings.py.

Enable FLATPAK_INDEX for pulp registry

---

manifests/apache.pp
spec/classes/plugin_container_spec.rb
spec/classes/pulpcore_spec.rb

Sometimes people end up with certificates that have uppercase letters in
the CN, but pass lowercase in the auth map.

always compare CNs as downcase

---

manifests/database.pp

some people use other names than `pulp` for their DB user

use the right username when computing the db password hash

---

manifests/config.pp
spec/classes/pulpcore_spec.rb

Without this a duplicate file resource is created.

Fixes #38679 - Handle overlapping import & export paths
